language: java # set desired language

sudo: true
dist: trusty

jdk:
  - oraclejdk8
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

addons:
   firefox: "52.0.2" # if your project contains tests need to be run on firefox include these lines


before_install:

  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024" # running virtual display on desired port with desired settings
  #- sleep 3


before_script:
  # Selenium server
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  #- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  #- sudo dpkg -i google-chrome*.deb
  - sleep 3
  - sudo apt-get update > /dev/null
  - java -jar selenium-server-standalone-3.0.1.jar > /dev/null 2>/dev/null & # starting selenium-server
  - sleep 10

script:
  - echo "Extracting firefox and setting PATH variable..."
  - tar -xjf /tmp/firefox-52.0.2.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - echo "Using firefox version `firefox --version`"
  - chmod +x /home/travis/build/Orfik/N2PS-AutoTests/src/test/resources/geckodriver_v.14
  - export PATH="$HOME/.chrome/chromium/chrome-linux/chrome:$PATH"
  - echo "Using chrome version `chrome --version`"
  - chmod +x /home/travis/build/Orfik/N2PS-AutoTests/src/test/resources/chromedriver
  - mvn help:active-profiles
  - mvn test
  - mvn site
  #- mvn jetty:run
deploy:
  provider: releases
  curl: -i https://api.github.com -u
  email: orfiik@gmail.com
  api-key:
   secure: QkIyRxP6PmCm6tj6dBBX5hvIn90/UIS12KFBAu8uMLpGljTLZDYV2Hy7WhN2kerp1bktNJojdzdce1zTrdbvGIJGV/WOK47xEHBIU74qkuVjr/TAF81gPOXeL53EK4xi4NhpNyTd2EQ3HikrWQfyb0TRH2Mhts/LbyVpwAlr9Hzent7jGYLKGtCeqt1TtY20gdKLs1mzfUZfHkM9vXPe6Z26Tz37zZcpkSycLgfGhl34fF6mlgMvlI+eBnDyqycsBzP908s+TP6KQAXb4ZIacMSzfqbRRT57Uwatx5emDJwoLc0gIePI+TBR+xOzF/yWDCXM/Sfwfh8BX/zHQ2nNhioMqWbOzteW9aVp8e6dLogbv3yQ7XFvZW6xHw+1d2XrhTdU4/M5zhicbk0mCzzC1GXkw3T9OZ4CxnGeMfOS8o4Xw/jriTONiqFJZ7J2c5cUdpMi3xH9+0TZvvbASXLqfe6O766OlO6dVdb83aJAtrdME3uI+r2i+LVKd1uI+Ni5uLYoNIYAKrXy38zbHMN8zfpXkGW3DEsfXXW0WvW5TURRMZivp9Gu/h9eBTfTASLQBDqV9U5fym17ysAz5LL1H6tMKcCSiZ1nJlM/BL4Q655pwB5PQjuIZ21/6QacLqsUezUmmaaJXIXBqBO/sesRyM0Qq97i50ykqTEEj8MtCnk="
  file: "/home/travis/build/Orfik/N2PS-AutoTests/target/site/allure-maven-plugin/"
  skip_cleanup: true
  on:
  tags: true
  repo: Orfik/N2PS-AutoTests


