language: java # set desired language

sudo: true
dist: trusty

jdk:
  - oraclejdk8
addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

addons:
   firefox: "52.0.2" # if your project contains tests need to be run on firefox include these lines


before_install:

  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024" # running virtual display on desired port with desired settings
  #- sleep 3


before_script:
  # Selenium server
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  #- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  #- sudo dpkg -i google-chrome*.deb
  - sleep 3
  - sudo apt-get update > /dev/null
  - java -jar selenium-server-standalone-3.0.1.jar > /dev/null 2>/dev/null & # starting selenium-server
  - sleep 10

script:
  - echo "Extracting firefox and setting PATH variable..."
  - tar -xjf /tmp/firefox-52.0.2.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - echo "Using firefox version `firefox --version`"
  - chmod +x /home/travis/build/Orfik/N2PS-AutoTests/src/test/resources/geckodriver_v.14
  - export PATH="$HOME/.chrome/chromium/chrome-linux/chrome:$PATH"
  - echo "Using chrome version `chrome --version`"
  - chmod +x /home/travis/build/Orfik/N2PS-AutoTests/src/test/resources/chromedriver
  - mvn help:active-profiles
  - mvn test
  - mvn site
  #- chmod +x /home/travis/build/Orfik/N2PS-AutoTests/target/allure-results
  #- mvn jetty:run

after_success:
    - cd /home/travis/build/Orfik/N2PS-AutoTests/target/site/allure-maven-plugin
    - git init
    - git config user.name "${GH_USER_NAME}"
    - git config user.email "{GH_USER_EMAIL}"
    - git add . ; git commit -m "Deploy to GitHub Pages"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF_FB}" master > /dev/null 2>&1

